_devices:
  bla:
    driver: unknown_driver
  time:
    driver: time
    format: "%F %T"
    local_time: true
    every_second: false

  time2:
    driver: time

  dummy1:
    driver: dummy
  dummy2:
    driver: dummy
  # dummy3:
  #   type: dummy
drivers:
  time:
    format: "%F %T"
    local_time: true
    every_second: false
  dummy:
  telnet:
    name: console_01
    listen_on: 127.0.0.1:7800
  esphome:
    connections:
      - name: bathroom_mirror
        host: 192.168.178.27:6053
        password: my_api_password
      - name: wc
        host: 192.168.178.26:6053
        password: my_api_password
