_devices:
  bla:
    driver: unknown_driver
  time:
    driver: time
    format: "%F %T"
    local_time: true
    every_second: false

  time2:
    driver: time

  dummy1:
    driver: dummy
  dummy2:
    driver: dummy
  # dummy3:
  #   type: dummy
drivers:
  time:
    format: "%F %T"
    local_time: true
    every_second: true
  dummy:
